In [3]:
#part1 data set understanding
import pandas as pd
df=pd.read_csv("/content/online_shopping_uncleaned_20000_rows.csv")
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1,1.0,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10days,NaN,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,NaN,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1,3.0,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,NaN,4.0,returned,chennai,15,NaN,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9688,9688,17450.0,F,California,17.0,35841.0,2019-08-16,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,20.0,unknown,2,NaN,NaN,NaN,10,high,NaN,gold
9689,9689,17450.0,F,California,17.0,35841.0,2019-08-16,GGOEGOFH020299,Galaxy Screen Cleaning Cloth,Office,...,20.0,FAILED,1,5.0,Returned,Delhi,5,Medium,0,Silver
9690,9690,17450.0,F,California,17.0,35841.0,2019-08-16,GGOEYFKQ020699,YouTube Custom Decals,Office,...,20.0,Paid,5,4.0,NaN,Mumbai,15,Low,4calls,Platinum
9691,9691,17450.0,F,California,17.0,35846.0,2019-08-16,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,20.0,Paid,2,4.0,Returned,Mumbai,15,high,4calls,Silver
9692,9692,17450.0,F,Cali,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#display the first 10 rows
df.head(10)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1,1.0,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10days,NaN,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,NaN,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1,3.0,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,NaN,4.0,returned,chennai,15,NaN,NaN,Platinum
5,5,17850.0,M,Chicago,12.0,16701.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,FAILED,2,2.0,NaN,Delhi,NaN,Low,2,Gold
6,6,17850.0,M,Chicago,12.0,16702.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,NaN,5.0,Not Returned,chennai,unknown,high,unknown,NaN
7,7,17850.0,M,Chicago,12.0,16703.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Pending,7,4.0,returned,Mumbai,10,Low,2,NaN
8,8,17850.0,M,Chicago,12.0,16704.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10days,4.0,returned,Delhi,5,High,0,Platinum
9,9,17850.0,M,Chicago,12.0,16710.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Paid,10days,NaN,Returned,Mumbai,5,unknown,NaN,Gold

In [ ]:
#display the last 10 rows
df.tail(10)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
19990,19990,14309.0,F,New Jersey,49.0,30594.0,2019-06-17,GGOEGOLC014299,Google Metallic Notebook Set,Office,...,30.0,Pending,1,1.0,NONE,NaN,unknown,NaN,NaN,NaN
19991,19991,14309.0,F,New Jersey,49.0,30595.0,2019-06-17,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,Paid,NaN,5.0,Not Returned,Chennai,15,NaN,2,Silver
19992,19992,15291.0,M,California,32.0,31203.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,paid,3,3.0,NaN,Unknown,5,unknown,unknown,NaN
19993,19993,16013.0,M,New York,31.0,31175.0,2019-06-25,GGOEAFKQ020599,Android Sticker Sheet Ultra Removable,Office,...,30.0,Pending,3,NaN,NaN,NaN,5,Low,3,NaN
19994,19994,16013.0,M,New York,31.0,31175.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,Paid,7,NaN,Not Returned,chennai,5,Low,3,gold
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,NaN,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3,NaN,NaN,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,NaN,2.0,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7,NaN,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,NaN,1,2.0,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
# Find the total number of rows and columns
df.shape

(20000, 30)

In [ ]:
#part2 data exploration
#display all column names
df.columns

Index(['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct',
       'Payment_Status', 'Delivery_Days', 'Customer_Rating', 'Return_Status',
       'Customer_City', 'Discount_Percent', 'Order_Priority', 'Support_Calls',
       'Membership'],
      dtype='object')

In [ ]:
#check data types of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           20000 non-null  int64
 1   CustomerID           20000 non-null  float64
 2   Gender               20000 non-null  object
 3   Location             20000 non-null  object
 4   Tenure_Months        20000 non-null  float64
 5   Transaction_ID       20000 non-null  float64
 6   Transaction_Date     20000 non-null  object
 7   Product_SKU          20000 non-null  object
 8   Product_Description  20000 non-null  object
 9   Product_Category     20000 non-null  object
 10  Quantity             20000 non-null  float64
 11  Avg_Price            20000 non-null  float64
 12  Delivery_Charges     20000 non-null  float64
 13  Coupon_Status        20000 non-null  object
 14  GST                  20000 non-null  float64
 15  Date                 20000 non-null  object
 16  Offline_Spend        20000 non-null  float64
 17  Online_Spend         20000 non-null  float64
 18  Month                20000 non-null  int64
 19  Coupon_Code          16644 non-null  object
 20  Discount_pct         19917 non-null  float64
 21  Payment_Status       16748 non-null  object
 22  Delivery_Days        17605 non-null  object
 23  Customer_Rating      15012 non-null  float64
 24  Return_Status        15924 non-null  object
 25  Customer_City        16579 non-null  object
 26  Discount_Percent     17151 non-null  object
 27  Order_Priority       16644 non-null  object
 28  Support_Calls        17144 non-null  object
 29  Membership           13283 non-null  object
dtypes: float64(11), int64(2), object(17)
memory usage: 4.6+ MB

In [ ]:
#display summary statistics
df.describe()

,Unnamed: 0,CustomerID,Tenure_Months,Transaction_ID,Quantity,Avg_Price,Delivery_Charges,GST,Offline_Spend,Online_Spend,Month,Discount_pct,Customer_Rating
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,19917.000000,15012.000000
mean,9999.500000,15384.448800,26.419000,31757.398950,4.403900,56.511256,11.07499,0.134707,2998.910000,1960.758028,6.345150,22.944219,3.175793
std,5773.647028,1790.469818,13.522188,10442.150226,21.192688,63.316612,20.61016,0.044485,1116.007655,849.627815,3.993798,7.820770,1.338989
min,0.000000,12347.000000,2.000000,16679.000000,1.000000,0.390000,0.00000,0.050000,500.000000,320.250000,1.000000,10.000000,1.000000
25%,4999.750000,13819.000000,15.000000,22285.000000,1.000000,6.180000,6.00000,0.100000,2000.000000,1296.810000,3.000000,20.000000,2.000000
50%,9999.500000,15311.000000,27.000000,34498.500000,1.000000,19.190000,6.50000,0.100000,3000.000000,1918.530000,8.000000,20.000000,4.000000
75%,14999.250000,17114.000000,38.000000,36871.000000,2.000000,119.000000,6.50000,0.180000,4000.000000,2546.580000,8.000000,30.000000,4.000000
max,19999.000000,18260.000000,50.000000,48497.000000,825.000000,355.740000,521.36000,0.180000,5000.000000,4055.300000,12.000000,30.000000,5.000000

In [ ]:
#Count unique values in each column
df.nunique()

Unnamed: 0             20000
CustomerID               889
Gender                     2
Location                   5
Tenure_Months             49
Transaction_ID         10153
Transaction_Date         154
Product_SKU             1012
Product_Description      385
Product_Category          20
Quantity                 111
Avg_Price                457
Delivery_Charges         185
Coupon_Status              3
GST                        4
Date                     154
Offline_Spend             11
Online_Spend             154
Month                      5
Coupon_Code                5
Discount_pct               3
Payment_Status             5
Delivery_Days              7
Customer_Rating            5
Return_Status              4
Customer_City              5
Discount_Percent           6
Order_Priority             5
Support_Calls              6
Membership                 4
dtype: int64

In [ ]:
#identify columns with missing values
df.isnull()

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,True,True,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,True
19996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,True,False,False
19997,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,True,False,False,True
19998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,True,False,False,False
19999,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False

In [ ]:
#part3 Missing value Handling
#count missing values in each column
df.isnull().sum()

Unnamed: 0                0
CustomerID                0
Gender                    0
Location                  0
Tenure_Months             0
Transaction_ID            0
Transaction_Date          0
Product_SKU               0
Product_Description       0
Product_Category          0
Quantity                  0
Avg_Price                 0
Delivery_Charges          0
Coupon_Status             0
GST                       0
Date                      0
Offline_Spend             0
Online_Spend              0
Month                     0
Coupon_Code            3356
Discount_pct             83
Payment_Status         3252
Delivery_Days          2395
Customer_Rating        4988
Return_Status          4076
Customer_City          3421
Discount_Percent       2849
Order_Priority         3356
Support_Calls          2856
Membership             6717
dtype: int64

In [5]:
#missing valuse replace mean value
x=df['Customer_Rating'].mean()
x
df['Customer_Rating'].fillna(df['Customer_Rating'].mean(),inplace=True)

/tmp/ipykernel_1489/3918119948.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer_Rating'].fillna(df['Customer_Rating'].mean(),inplace=True)

In [ ]:
print(x)

3.175792699173994

In [6]:
df['Customer_Rating']

0       1.000000
1       3.170685
2       3.170685
3       3.000000
4       4.000000
          ...
9688    3.170685
9689    5.000000
9690    4.000000
9691    4.000000
9692    3.170685
Name: Customer_Rating, Length: 9693, dtype: float64

In [ ]:
#replace missing values in payment_status with unknown
df['Payment_Status'].fillna('unknown')

0        Pending
1        unknown
2        unknown
3           Paid
4        Pending
          ...
19995    unknown
19996       Paid
19997      paid
19998    Pending
19999    unknown
Name: Payment_Status, Length: 20000, dtype: object

In [ ]:
df['Delivery_Days'].fillna(0,inplace=True)

In [ ]:
df['Delivery_Days'].median()

3.0

In [ ]:
#fill missing values in delivery_day using median
df['Delivery_Days'] = (
    df['Delivery_Days']
    .astype(str)
    .str.replace('days', '', regex=False)
    .str.strip()
)

df['Delivery_Days'] = pd.to_numeric(df['Delivery_Days'], errors='coerce')

df['Delivery_Days'].fillna(df['Delivery_Days'].median(), inplace=True)

/tmp/ipykernel_5011/2832535436.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Delivery_Days'].fillna(df['Delivery_Days'].median(), inplace=True)

In [ ]:
df['Delivery_Days']

0         1.0
1        10.0
2         5.0
3         1.0
4         0.0
         ...
19995     1.0
19996     3.0
19997     0.0
19998     7.0
19999     1.0
Name: Delivery_Days, Length: 20000, dtype: float64

In [ ]:
#replace misising coupon_code with no Coupon
df['Coupon_Code'].fillna("No Coupon")

In [ ]:
df

In [ ]:
#part 4 string cleaning
#remove leading and trailing spaces in all string columns
str_cols = df.select_dtypes(include=['object'])

df[str_cols.columns] = str_cols.apply(lambda x: x.str.strip())

In [ ]:
df.columns

In [ ]:
#convert payment status to lowercase
df['Payment_Status']=df['Payment_Status'].str.lower()

In [ ]:
df['Payment_Status']

In [ ]:
#standardize values in Customer_city
df['Customer_City'] = df['Customer_City'].str.strip().str.lower().str.title()

In [ ]:
df['Customer_City']

In [ ]:
#clean coupon code(remove extra spaces and make uppercase)
df["Coupon_Code"]=df["Coupon_Code"].str.strip().str.upper()

In [ ]:
df["Coupon_Code"]

In [7]:
#numpy import
#replace unknown values with NaN
import numpy as np
df.replace("unknown", np.nan, inplace=True)

In [ ]:
df

In [ ]:
#replace None and   NONE with NaN

df.replace(['NONE', 'none'], np.nan, inplace=True)

In [ ]:
df.columns

In [ ]:
#convert delivery days to numeric remove days
df['Delivery_Days'] = (
    df['Delivery_Days']
    .astype(str)
    .str.replace('days', '', regex=False)
    .str.strip()
)

df['Delivery_Days'] = pd.to_numeric(df['Delivery_Days'], errors='coerce')

In [ ]:
df['Delivery_Days']

In [ ]:
df['Delivery_Days'].astype(int)

In [ ]:
df['Delivery_Days'].dtypes

In [ ]:
df.columns

In [ ]:
#convert discount percent into numeric(reemove%)
#(regex= normal string, coerce=its not show errors replaced by nan)
df['Discount_Percent'] = (
    df['Discount_Percent']
    .astype(str)
    .str.replace('%', '', regex=False)
    .str.strip()
)

df['Discount_Percent'] = pd.to_numeric(df['Discount_Percent'], errors='coerce')

In [ ]:
df['Discount_Percent']

In [ ]:
#convert support calls to numeric(remove calls)
df['Support_Calls']=(df['Customer_Rating'].astype(str).str.replace('calls','',regex=False).str.strip())

In [ ]:
df['Support_Calls']

In [ ]:
#convert Customer_Rating to numeric
df['Customer_Rating'] = pd.to_numeric(df['Customer_Rating'], errors='coerce')

In [ ]:
#handle invalid numeric values
print(df['Customer_Rating'].isnull().sum())

In [ ]:
#handled invalid numeric values
print(df.info())
df.duplicated()

In [ ]:
#check missing values
print(df.isnull().sum())

In [ ]:
#remove duplicates
df.drop_duplicates(inplace=True)

In [ ]:
#part6 Duplicate Handling
df.duplicated()
df.duplicated().sum()

In [ ]:
#remove duplicate rows
df.drop_duplicates(inplace=True)

In [ ]:
#display dataset shape after removal
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1,1.000000,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10days,3.175793,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,3.175793,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1,3.000000,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,0,4.000000,returned,chennai,15,NaN,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,3.175793,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3,3.175793,NaN,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,0,2.000000,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7,3.175793,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,NaN,1,2.000000,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
df.shape[0]

20000

In [ ]:
df.columns

In [ ]:
#part7
#count total number of orders
total_orders = len(df)

print("Total Orders:", total_orders)

Total Orders: 20000

In [ ]:
#Find number of orders by Payment_Status.
df['Payment_Status'].value_counts()

Payment_Status
FAILED     3430
 paid      3406
Pending    3337
Paid       3221
Name: count, dtype: int64

In [ ]:
#Identify most common payment method/status.
df['Payment_Status'].value_counts().idxmax()

'FAILED'

In [ ]:
df['Payment_Status'].value_counts().head(1)

Payment_Status
FAILED    3430
Name: count, dtype: int64

In [ ]:
#Identify most common payment method/status.
df['Return_Status'].value_counts()

Return_Status
NONE            4074
 returned       3990
Not Returned    3976
Returned        3884
Name: count, dtype: int64

In [ ]:
df.columns

Index(['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct',
       'Payment_Status', 'Delivery_Days', 'Customer_Rating', 'Return_Status',
       'Customer_City', 'Discount_Percent', 'Order_Priority', 'Support_Calls',
       'Membership'],
      dtype='object')

In [ ]:
#calcualte return percentage
Return_Status = (df['Return_Status'].value_counts().get('Yes', 0) / len(df)) * 100

print("Return_Status:", Return_Status)

Return_Status: 0.0

In [ ]:
returned_orders = 3990
total_orders = 20000

percentage = (returned_orders / total_orders) * 100

print(percentage)

19.950000000000003

In [ ]:
df['Return_Status'].value_counts()

Return_Status
NONE            4074
 returned       3990
Not Returned    3976
Returned        3884
Name: count, dtype: int64

In [ ]:
#Count orders by Order_Priority.
df['Order_Priority'].value_counts()

Order_Priority
High      3396
Low       3335
 high     3312
Medium    3257
Name: count, dtype: int64

In [ ]:
#Part 8 – Customer Analysis
#Count number of customers by Customer_City.
df['Customer_City'].value_counts()

Customer_City
Mumbai       3403
Chennai      3315
Unknown      3312
Delhi        3284
 chennai     3265
Name: count, dtype: int64

In [ ]:
#Find city with highest orders.
df['Customer_City'].value_counts().idxmax()

'Mumbai'

In [ ]:
#Find average Customer_Rating.
df['Customer_Rating'].mean()

np.float64(3.175792699173994)

In [ ]:
#Identify customers with rating less than 3.
df[df['Customer_Rating'] < 3]

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1.0,1.0,returned,Unknown,25%,High,3,Gold
5,5,17850.0,M,Chicago,12.0,16701.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,FAILED,2.0,2.0,NaN,Delhi,NaN,Low,2,Gold
16,16,17850.0,M,Chicago,12.0,16722.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,paid,2.0,2.0,Returned,Delhi,15,NaN,NaN,Gold
24,24,13047.0,M,California,43.0,16684.0,2019-01-01,GGOENEBQ079199,Nest Protect Smoke + CO White Wired Alarm-USA,Nest-USA,...,10.0,FAILED,7.0,2.0,Returned,Delhi,5,Low,3,Platinum
29,29,14688.0,F,New York,46.0,16732.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,10.0,1.0,returned,Chennai,NaN,high,NaN,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19981,19981,14401.0,F,California,20.0,29465.0,2019-06-02,GGOEGOLC014299,Google Metallic Notebook Set,Office,...,30.0,NaN,3.0,2.0,Returned,Chennai,NaN,Medium,NaN,NaN
19985,19985,15194.0,M,Chicago,33.0,30614.0,2019-06-17,GGOEGGOA017399,Maze Pen,Office,...,30.0,NaN,7.0,2.0,Returned,Mumbai,10,high,3,Silver
19990,19990,14309.0,F,New Jersey,49.0,30594.0,2019-06-17,GGOEGOLC014299,Google Metallic Notebook Set,Office,...,30.0,Pending,1.0,1.0,NONE,NaN,NaN,NaN,NaN,NaN
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,0.0,2.0,Not Returned,Mumbai,NaN,NaN,NaN,NaN
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,NaN,1.0,2.0,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
#Count customers by Membership type.
membership_count = df['Membership'].value_counts()
print(membership_count)

Membership
Gold        3342
Silver      3338
Platinum    3327
 gold       3276
Name: count, dtype: int64

In [ ]:
#Part 9 – Delivery Analysis
Find average Delivery_Days.
df['Delivery_Days'].mean()

np.float64(3.8664)

In [ ]:
df.columns

Index(['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct',
       'Payment_Status', 'Delivery_Days', 'Customer_Rating', 'Return_Status',
       'Customer_City', 'Discount_Percent', 'Order_Priority', 'Support_Calls',
       'Membership'],
      dtype='object')

In [ ]:
#Identify orders with delivery time > 7 days.
df[df['Delivery_Days'] > 7]

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10.0,NaN,NaN,NaN,25%,Medium,4calls,NaN
8,8,17850.0,M,Chicago,12.0,16704.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10.0,4.0,returned,Delhi,5,High,0,Platinum
9,9,17850.0,M,Chicago,12.0,16710.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Paid,10.0,NaN,Returned,Mumbai,5,NaN,NaN,Gold
18,18,17850.0,M,Chicago,12.0,16723.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,NaN,10.0,4.0,NaN,Delhi,25%,High,NaN,gold
29,29,14688.0,F,New York,46.0,16732.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,10.0,1.0,returned,Chennai,NaN,high,NaN,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19944,19944,13078.0,F,California,28.0,29486.0,2019-06-02,GGOEYOLR018699,YouTube Leatherette Notebook Combo,Office,...,30.0,NaN,10.0,NaN,Not Returned,NaN,15,High,NaN,gold
19947,19947,17912.0,M,New Jersey,7.0,29415.0,2019-06-02,GGOEGGOA017399,Maze Pen,Office,...,30.0,NaN,10.0,3.0,Returned,Chennai,NaN,NaN,NaN,Silver
19959,19959,12867.0,M,Chicago,32.0,29423.0,2019-06-02,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,Paid,10.0,4.0,returned,chennai,NaN,NaN,NaN,NaN
19967,19967,13846.0,F,New Jersey,4.0,29407.0,2019-06-02,GGOEGOAQ018099,Pen Pencil & Highlighter Set,Office,...,30.0,Pending,10.0,3.0,Returned,Mumbai,NaN,High,NaN,Silver
19984,19984,15194.0,M,Chicago,33.0,30614.0,2019-06-17,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,10.0,4.0,returned,Mumbai,15,NaN,3,Platinum

In [ ]:
#count delayed orders
delayed_orders = df[df['Delivery_Days'] > 7]
print("Delayed Orders Count:", len(delayed_orders))

Delayed Orders Count: 2452

In [ ]:
#compare delivery time by order priority
priority_delivery = df.groupby('Order_Priority')['Delivery_Days'].mean()
print(priority_delivery)

Order_Priority
 high     3.833635
High      3.873380
Low       3.860870
Medium    3.858152
Name: Delivery_Days, dtype: float64

In [ ]:
df.columns

Index(['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct',
       'Payment_Status', 'Delivery_Days', 'Customer_Rating', 'Return_Status',
       'Customer_City', 'Discount_Percent', 'Order_Priority', 'Support_Calls',
       'Membership'],
      dtype='object')

In [ ]:
#Find fastest delivery category.
fastest_category = df.groupby('Product_Category')['Delivery_Days'].mean().idxmin()
print("Fastest Delivery Category:", fastest_category)

Fastest Delivery Category: Android

In [ ]:
#Part 10 – Discount & Coupon Analysis
#find average discount_percent
df["Discount_Percent"].mean()

np.float64(14.999302260675412)

In [ ]:
df.columns

Index(['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct',
       'Payment_Status', 'Delivery_Days', 'Customer_Rating', 'Return_Status',
       'Customer_City', 'Discount_Percent', 'Order_Priority', 'Support_Calls',
       'Membership'],
      dtype='object')

In [ ]:
#Identify orders with highest discount
df['Discount_Percent'].max()

25.0

In [ ]:
df['Coupon_Status']

0            Used
1            Used
2        Not Used
3         Clicked
4         Clicked
           ...
19995    Not Used
19996     Clicked
19997        Used
19998        Used
19999        Used
Name: Coupon_Status, Length: 20000, dtype: object

In [ ]:
#Count how many orders used coupons.
coupon_used = df[df['Coupon_Status'] == 'Used'].shape[0]
print("Coupons Used Orders:", coupon_used)

Coupons Used Orders: 6761

In [ ]:
#Find most used Coupon_Code.
df['Coupon_Code'].value_counts().idxmax()

'NONE'

In [ ]:
df.columns

Index(['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct',
       'Payment_Status', 'Delivery_Days', 'Customer_Rating', 'Return_Status',
       'Customer_City', 'Discount_Percent', 'Order_Priority', 'Support_Calls',
       'Membership'],
      dtype='object')

In [ ]:
df['Support_Calls']

0             3
1        4calls
2             0
3             3
4           NaN
          ...
19995    4calls
19996         2
19997       NaN
19998    4calls
19999    4calls
Name: Support_Calls, Length: 20000, dtype: object

In [ ]:
#Find average Support_Calls per order.
df['Support_Calls'] = pd.to_numeric(df['Support_Calls'], errors='coerce')
avg_support_calls = df['Support_Calls'].mean()
print(avg_support_calls)

1.498913893474672

In [ ]:
#Identify orders with more than 2 support calls.
df[df['Support_Calls'] > 2]

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1.0,1.0,returned,Unknown,25.0,High,3.0,Gold
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1.0,3.0,returned,chennai,NaN,Low,3.0,Gold
19,19,17850.0,M,Chicago,12.0,16724.0,2019-01-01,GGOENEBB078899,Nest Cam Indoor Security Camera - USA,Nest-USA,...,10.0,FAILED,3.0,5.0,NaN,Unknown,5.0,High,3.0,Gold
24,24,13047.0,M,California,43.0,16684.0,2019-01-01,GGOENEBQ079199,Nest Protect Smoke + CO White Wired Alarm-USA,Nest-USA,...,10.0,FAILED,7.0,2.0,Returned,Delhi,5.0,Low,3.0,Platinum
26,26,13047.0,M,California,43.0,16689.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,7.0,4.0,returned,Unknown,5.0,high,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19984,19984,15194.0,M,Chicago,33.0,30614.0,2019-06-17,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,10.0,4.0,returned,Mumbai,15.0,NaN,3.0,Platinum
19985,19985,15194.0,M,Chicago,33.0,30614.0,2019-06-17,GGOEGGOA017399,Maze Pen,Office,...,30.0,NaN,7.0,2.0,Returned,Mumbai,10.0,high,3.0,Silver
19988,19988,18116.0,F,Chicago,38.0,30616.0,2019-06-17,GGOEGOAQ012899,Ballpoint LED Light Pen,Office,...,30.0,NaN,1.0,NaN,NONE,NaN,25.0,NaN,3.0,Silver
19993,19993,16013.0,M,New York,31.0,31175.0,2019-06-25,GGOEAFKQ020599,Android Sticker Sheet Ultra Removable,Office,...,30.0,Pending,3.0,NaN,NaN,NaN,5.0,Low,3.0,NaN
19994,19994,16013.0,M,New York,31.0,31175.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,Paid,7.0,NaN,Not Returned,chennai,5.0,Low,3.0,gold

In [ ]:
#Find relation between Support_Calls and Return_Status.
df.groupby('Return_Status')['Support_Calls'].mean()

Return_Status
 returned       1.513255
NONE            1.493413
Not Returned    1.494034
Returned        1.479434
Name: Support_Calls, dtype: float64

In [ ]:
#Identify problematic orders (high calls + returns).
problematic_orders = df[(df['Support_Calls'] > 2) & (df['Return_Status'] == 'Returned')]
print(problematic_orders)

       Unnamed: 0  CustomerID Gender    Location  Tenure_Months  \
24             24     13047.0      M  California           43.0
43             43     17511.0      F     Chicago           25.0
180           180     17920.0      F  California           18.0
212           212     14606.0      F     Chicago           33.0
239           239     15694.0      F    New York           41.0
...           ...         ...    ...         ...            ...
19925       19925     17551.0      M     Chicago           32.0
19943       19943     16817.0      M  California           20.0
19974       19974     13846.0      F  New Jersey            4.0
19975       19975     13846.0      F  New Jersey            4.0
19985       19985     15194.0      M     Chicago           33.0

       Transaction_ID Transaction_Date     Product_SKU  \
24            16684.0       2019-01-01  GGOENEBQ079199
43            16826.0       2019-01-03  GGOENEBJ079499
180           17068.0       2019-01-04  GGOENEBQ079099
212           17970.0       2019-01-16  GGOENEBB078899
239           18013.0       2019-01-16  GGOENEBQ079199
...               ...              ...             ...
19925         29961.0       2019-06-09  GGOEGOAQ020099
19943         29478.0       2019-06-02  GGOEYOLR018699
19974         29410.0       2019-06-02  GGOEAFKQ020599
19975         29411.0       2019-06-02  GGOEGOGA016299
19985         30614.0       2019-06-17  GGOEGGOA017399

                                     Product_Description Product_Category  \
24         Nest Protect Smoke + CO White Wired Alarm-USA         Nest-USA
43     Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA
180      Nest Protect Smoke + CO White Battery Alarm-USA         Nest-USA
212                Nest Cam Indoor Security Camera - USA         Nest-USA
239        Nest Protect Smoke + CO White Wired Alarm-USA         Nest-USA
...                                                  ...              ...
19925                         Four Color Retractable Pen           Office
19943                 YouTube Leatherette Notebook Combo           Office
19974              Android Sticker Sheet Ultra Removable           Office
19975                        Grip Highlighter Pen 3 Pack           Office
19985                                           Maze Pen           Office

       ...  Discount_pct  Payment_Status  Delivery_Days Customer_Rating  \
24     ...          10.0          FAILED            7.0             2.0
43     ...          10.0          FAILED            2.0             NaN
180    ...          10.0         Pending            2.0             4.0
212    ...          10.0           paid            10.0             1.0
239    ...          10.0           paid             2.0             1.0
...    ...           ...             ...            ...             ...
19925  ...          30.0            Paid            0.0             2.0
19943  ...          30.0            Paid            2.0             4.0
19974  ...          30.0             NaN            0.0             4.0
19975  ...          30.0          FAILED            3.0             NaN
19985  ...          30.0             NaN            7.0             2.0

       Return_Status Customer_City  Discount_Percent  Order_Priority  \
24          Returned         Delhi               5.0             Low
43          Returned       Unknown              10.0             NaN
180         Returned         Delhi              10.0             NaN
212         Returned        Mumbai              10.0           high
239         Returned       Unknown              10.0           high
...              ...           ...               ...             ...
19925       Returned       Unknown              15.0             Low
19943       Returned         Delhi              10.0          Medium
19974       Returned         Delhi              10.0          Medium
19975       Returned        Mumbai               NaN          Medium
19985       Returned        Mumbai              10.0           high

       Support_Calls Membership
24               3.0   Platinum
43               3.0        NaN
180              3.0        NaN
212              3.0       Gold
239              3.0      gold
...              ...        ...
19925            3.0        NaN
19943            3.0      gold
19974            3.0        NaN
19975            3.0       Gold
19985            3.0     Silver

[567 rows x 30 columns]

In [ ]:
#save cleaned data set
df.to_csv("clean_online_shopping.csv", index=False)

In [ ]:
#export analysis to csv
df.to_csv("output.csv", index=False)

In [ ]:
#display final datset shape
print("Final Dataset Shape:", df.shape)

Final Dataset Shape: (20000, 30)

In [ ]:
from google.colab import files
files.download("clean_online_shopping.csv")